CREATE TABLE PROVIDERS(
       NPI STRING,
       PVD_LEGAL_LAST_NAME STRING,
       PVD_LEGAL_FIRST_NAME STRING,       
       PVD_1ST_LINE_BU_MAILING_ADD STRING,
       PVD_BU_MAILING_ADD_CITY_NAME STRING,
       PVD_BU_MAILING_ADD_ST_NAME STRING,  
       PVD_BU_MAILING_ADD_POSTAL_CD STRING,
       PVD_GENDER_CODE STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LOCATION '/user/admin/finalproject/providers'
tblproperties ("skip.header.line.count"="1");   
